package com.example.ouamar.ouamsapp.entite;

import com.j256.ormlite.field.DatabaseField;

/**
 * Created by Ouamar on 18/10/2015.
 */
public class Note {


    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    long id;
    @DatabaseField(canBeNull = false)
    String titre;
    @DatabaseField(canBeNull = false)
    String notes;
    @DatabaseField(foreign = true, foreignAutoRefresh = true,canBeNull = false, foreignAutoCreate = true)
    User idUser;


    Note() {
        // needed by ormlite
    }


    public Note( User idUser, String notes, String titre) {

        this.idUser = idUser;
        this.notes = notes;
        this.titre = titre;
    }

    public User getIdUser() {
        return idUser;
    }

    public long getId() {
        return id;
    }

    public String getNotes() {
        return notes;
    }



    public String getTitre() {
        return titre;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public void setTitre(String titre) {
        this.titre = titre;
    }

    @Override
    public String toString() {
        return "Note{" +
                "id=" + id +
                ", titre='" + titre + '\'' +
                ", notes='" + notes + '\'' +
                ", idUser=" + idUser +
                '}';
    }
}


