package com.example.ouamar.ouamsapp.entite;

import com.j256.ormlite.field.DatabaseField;

/**
 * Created by Ouamar on 18/10/2015.
 */
public class User {

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    long id;
    @DatabaseField(canBeNull = false)
    String password;
    @DatabaseField(canBeNull = false,unique = true)
    String pseudo;
    @DatabaseField(canBeNull = false, unique = true)
    String email;


    User() {
        // needed by ormlite
    }


    public User(String email, String pseudo, String password) {
        this.email = email;
        this.pseudo = pseudo;
        this.password = password;
    }

    public long getId() {
        return id;
    }

    public String getPseudo() {
        return pseudo;
    }

    public String getEmail() {
        return email;
    }

    public boolean isPasswordEqual(String password){
         return this.password.equals(password);
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", password='" + password + '\'' +
                ", pseudo='" + pseudo + '\'' +
                ", email='" + email + '\'' +
                '}';
    }
}